name: build
on:
- push
- pull_request
jobs:
  build:
    name: java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 17
          - 21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle
      - run: ./gradlew check jacocoTestReport
      - uses: codecov/codecov-action@v3
